[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[global]
dataFrameSerialization = "legacy"

[theme]
primaryColor = "#1565c0"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif" 